### PR TITLE
Add AFR using tvQuickActions

### PR DESCRIPTION
**Pull request by vodik7**
I am developer of tvQuickActions and I found the way to switch frame rate using Accessibility Service for devices without system AFR. But it is no way to get video frame rate from system. So I need get this info from apps. It will be great if your application will be able to send data to my application.
At the moment, this method works on consoles with an Amlogic processor and has been tested on devices such as TiVo Stream 4K, Mecool KM9 Pro and Mecool KM6 Deluxe.

### CODE REVIEW

**Comment by moneytoo** [comment]
Just Player should already be able switch frame rate using system API on its own. I do not fully understand what this is for?

**Comment by vodik7** [comment]
Unfortunately, on many devices there is no system API for switching frame rate. Even Google Chromecast doesn't have a system API to switch frane rate. So my way will add switching frame rates for a lot of devices (f.e. TiVo Stream 4K, Mecool KM9 Pro, Mecool KM6 Deluxe, Homatics Dongle/Box Q, Mecool KM2, a lot of chinese devices and more)

**Comment by moneytoo** [comment]
In case of Chromecast with Google TV, it should support at least their seamless refresh rate switching when running Android 11.

**Comment by vodik7** [comment]
But it still on Android 10. And even if Chromecast with Google TV get update to 11 or 12, a lot of devices doesn't get updates to 11 or 12.

**Comment by vladlenas** [comment]
> In case of Chromecast with Google TV, it should support at least their seamless refresh rate switching when running Android 11.

As far as I heard, it will only be in 12 Android TV. 
I now have Chromecast with Google TV and Tivo Stream 4K. There is not enough AFR for a pleasant video viewing.

**Comment by artem011982** [comment]
Please, add this function. It will be very helpful for the boxes, that didn't support afr. Very many people will be grateful to you

**Comment by vovan22298** [comment]
Буду весьма благодарен если добавите данную функцию, многим будет гараздо приятнее смотреть тв, и популярность вашего плеера ещё больше возрастёт! Спасибо 🖐️

**Comment by vodik7** [comment]
Bro, even SmartTubeNext added it
https://github.com/yuliskov/SmartTubeNext/commit/9c6f12d9e5321536e360a9fc0efbd00a491e6a9b
https://github.com/yuliskov/SmartTubeNext/commit/faff69e1906891253fdbbebb0c141bd59dcdb0c5
https://github.com/yuliskov/SmartTubeNext/commit/443d81b195a68357f3d3603820dafe5e699618e0

**Comment by Loncaster** [comment]
This is a really important feature. Complete pls.

**Pull request closed without merging**
